### ISSUE TITLE
[QUESTION] What are the orientations of the basis elements?

### ISSUE THREAD

**Issue by Ziriax** [jeremyong/klein#10]
In your PGA library, I  guess the e1, e2, e3 basis elements correspond to the YZ, ZX and XY planes (so the planes x=0, y=0, z=0). Is that correct? Is the orientation also correct, e.g. e1 has orientation Y-direction towards Z-direction, e2 Z to X, and e3 X to Y?

And I guess e0 corresponds to the "plane at infinity" (w=0). Is it possible to also assign/visualize an orientation to e0? For example, when I'm looking at e0 along any direction vector (imagining e0 are the "stars" on a "sphere at infinity") does it have a clockwise or counter-clockwise orientation?

I'm porting your code to C#, and I'm trying to add some more comments to the code, but I don't fully understand PGA yet... I'm re-reading Charles Gunns SIGGRAPH paper to get a grip on it.

Maybe I should ask these questions on the bivector.net forum or discord?

**Comment by enkimute** [comment]
I'll give you a hint ;) Imagine hairs on the celestial sphere and comb them..

**Comment by jeremyong** [comment]
To me at least, e0 is simply "orthogonal" to e1, e2, and e3 :). In other words, e1 e2 and e3 on their own technically don't know if they've been assigned to "x" or "y" or "z." That is simply how we choose to interpret them but if we shuffled the axes around, all the operations would continue to work. Geometric algebra doesn't impart an innate "handedness" to a coordinate system the way the cross product does also (where the right hand rule is a necessary convention). I've personally found that a far more productive way to work with GA is to consider the basis elements themselves algebraically (from a group-theoretic standpoint), but then to consider the GA objects via their actions under the geometric product geometrically. That is, something like a e0 + b e1 + c e2 + d e3 "acts like a reflection" or "represents a plane" (by the same token). For these primitives, the correspondence between algebra and geometry is direct and doesn't need a lot of handwavy interpretation. I think try too hard to impart a geometric interpretation to individual pieces of the algebra can be a little detrimental because in the fuller clifford algebra, there are plenty of objects you can construct (like 3 + 2e1 - 5e0123) which simply don't have any natural geometric interpretation that I'm aware of.

**Comment by Ziriax** [comment]
> I'll give you a hint ;) Imagine hairs on the celestial sphere and comb them..

There are many ways to comb these hairs lol ;-) So I have no clue really. I could comb them towards the "origin", away from it, clockwise, counter clockwise, ...

**Comment by jeremyong** [comment]
So long as it's "orthogonal" to the other basis elements, you're fine and any visual representation is appropriate. There is no "correct" direction per se and anyone that claims otherwise is lying :)

**Comment by Ziriax** [comment]
This [long old introduction to PGA](https://arxiv.org/pdf/1307.2917.pdf) seems to talk about it, going to read it, although it might be superseded by Charles new work.

Closing this now, thanks for the help, also to @enkimute  and Charles.
